name: Run Cybersecurity Classification

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-classification:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn

    - name: Run classification script
      run: python cybersecurity_classification.py
